### PR TITLE
Fix broken anchors references in pnpm build

### LINKED ISSUE #1286: Fix broken anchor references in pnpm build
Running `pnpm build` gives us:

```
Please check the pages of your site in the list below, and make sure you don't reference any anchor that does not exist.
Note: it's possible to ignore broken anchors with the 'onBrokenAnchors' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /404.html:
   -> linking to #ask (resolved as: /404.html#ask)
- Broken anchor on source page path = /blog:
   -> linking to #ask (resolved as: /blog#ask)
- Broken anchor on source page path = /blog/2023-11-18-la-wallet:
   -> linking to #ask (resolved as: /blog/2023-11-18-la-wallet#ask)
- Broken anchor on source page path = /blog/2024-01-09-dif-hackathon-winners:
   -> linking to #ask (resolved as: /blog/2024-01-09-dif-hackathon-winners#ask)
- Broken anchor on source page path = /blog/2024-01-11-devcareer-hackathon-winners:
   -> linking to #ask (resolved as: /blog/2024-01-11-devcareer-hackathon-winners#ask)
- Broken anchor on source page path = /blog/2024-01-29-tbd-hackathon-winners:
   -> linking to #ask (resolved as: /blog/2024-01-29-tbd-hackathon-winners#ask)
...more
```

1. Ensure no actual links on the site are broken
2. Remove the warnings

### PR DESCRIPTION
**Pull request by ozipi**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR fixes this https://github.com/TBD54566975/developer.tbd.website/issues/1286. 

## Related Tickets & Documents

Resolves #1286 

## Added code snippets?
- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note
Added fixes for the pnpm build command, added fixes to the links in the mdx files and seeing the following -> https://docusaurus.io/docs/docusaurus-core#useBrokenLinks i did added them to the layout, please let me know if that's the correct place for you guys.

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [X] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: site/src/theme/Layout/index.js [hunk 1]
```diff
@@ -11,6 +12,13 @@ import { LanguageOptionsProvider } from '../../components/language/SupportedLang
 
 export default function LayoutWrapper(props) {
   const { hash } = useLocation();
+  useBrokenLinks().collectAnchor("ask");
```
Comment (angiejones) [inline site/src/theme/Layout/index.js:15]: how come these are needed?

Comment (ozipi) [reply site/src/theme/Layout/index.js:15]: ah!, basically i did a quick search on the broken anchors error when building and found out a couple things:

Docusaurus 3.1 [introduced](https://docusaurus.io/blog/releases/3.1#broken-anchors-checker) the `Broken anchors checker` and seems like it has some problems/false positives.

Couple of alternatives to fix it:
- Use the `collectAnchor` from the `useBrokenLinks` React hook API to make Docusaurus is aware of the anchors (works but a bit ugly).
 https://github.com/facebook/docusaurus/issues/9721#issuecomment-1882898840
- [Use The Docusaurus Link](https://github.com/facebook/docusaurus/issues/9763#issuecomment-1905657358) component to create the links in MDX, which it didn't work when testing in `site/docs/tbdex/wallet/get-offerings.mdx` file.
`<Link id="offering-object" to="/docs/tbdex/pfi/creating-offerings#offering-object">Offering</Link>`
Instead of
`[Offering](/docs/tbdex/pfi/creating-offerings#offering-object)`
- Just [Wait for 3.2 version](https://github.com/facebook/docusaurus/issues/9721#issuecomment-1968471438) sounds like there possibly the brokenanchors warns will be fixed.

Having the collectAnchor lines removes the warn but possibly is not the desired fix, i can remove this file changes and just leave the markdown trailing slash fixes if we want to wait and watch for version `3.2`.

**Review by angiejones — APPROVED** [review]

**Comment by angiejones** [comment]
thank you very much for this contribution! much appreciated 🙏🏾

**Comment by ALRubinger** [comment]
@ozipi THANK YOU for this and welcome to the TBD Community!

**Comment by ozipi** [comment]
Thank you both @angiejones @ALRubinger !! 🥳
