### PR TITLE
Fixed Import CDN statements. 

### LINKED ISSUE #774: Fix import statements on Web5 API Guide
On the [Web5 API Reference Guide](https://developer.tbd.website/api/web5-js#import) home page, the CDN import statements are not correct:

image

Those are the install statements. For Import, they should be:

> ```js
> import { Web5 } from 'https://unpkg.com/@web5/api@0.8.1/dist/browser.js';
> ```
> 
> or
> 
> ```js
> import { Web5 } from 'https://cdn.jsdelivr.net/npm/@web5/api@0.8.1/dist/browser.mjs'
> ```

Before picking up this issue, please note that it is not hardcoded in the doc. It needs to be fixed in the [SrcScript widget](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/src/components/ScriptSrc.jsx) but don't break the Install instructions

### PR DESCRIPTION
**Pull request by sayanta2005**
Added a new component for Import statements

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Added a new component named ImportSRC to render Import CDN statements rather than rendering from ScriptSRC itself. 

## Related Tickets & Documents

Resolves #774 

### Before:
image

### After:
image

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: site/src/components/ImportSrc.jsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+function ImportSrc(site) {
+  const {
+    siteConfig: { customFields },
+  } = useDocusaurusContext();
+
+  if (site.src === "unpkg") {
+    return (
+      <CodeBlock language="js">
+        {`import { Web5 } from 'https://unpkg.com/@web5/api@0.8.1/dist/browser.js';`}
```
Comment (angiejones) [inline site/src/components/ImportSrc.jsx:13]: please use the version variable instead of hardcoding it
`${customFields.WEB5_VERSION}`

File: site/src/components/ImportSrc.jsx [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+      </CodeBlock>
+    );
+  } else {
+    return (
+      <CodeBlock language="js">
+        {`import { Web5 } from 'https://cdn.jsdelivr.net/npm/@web5/api@0.8.1/dist/browser.mjs'`}
```
Comment (angiejones) [inline site/src/components/ImportSrc.jsx:19]: please use the version variable

**Review by angiejones — CHANGES_REQUESTED** [review]

File: site/src/components/ImportSrc.jsx (hunk 1 above)
Comment (sayanta2005) [reply site/src/components/ImportSrc.jsx:13]: Okay, working on it.

**Comment by sayanta2005** [comment]
I've made the required changes. Please check it once and tell me if anything more is required.

**Review by angiejones — APPROVED** [review]

**Comment by angiejones** [comment]
@EbonyLouis hacktoberfest
